config/routes.rb
Rails.application.routes.draw do
  resources :pediatrics
  resources :caps
  get 'index/home'
  get 'index/search'
  get 'index/about'
  get 'index/contact'
  root 'index#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users
  resources :microposts
  resource :replies
  resources :identities

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]
end

app/models/pediatric.rb
class Pediatric < ApplicationRecord
end

app/controllers/pediatrics_controller.rb
class PediatricsController < ApplicationController
  before_action :set_pediatric, only: [:show, :edit, :update, :destroy]

  # GET /pediatrics
  # GET /pediatrics.json
  def index
    @pediatrics = Pediatric.all
  end

  # GET /pediatrics/1
  # GET /pediatrics/1.json
  def show
  end

  # GET /pediatrics/new
  def new
    @pediatric = Pediatric.new
  end

  # GET /pediatrics/1/edit
  def edit
  end

  # POST /pediatrics
  # POST /pediatrics.json
  def create
    @pediatric = Pediatric.new(pediatric_params)

    respond_to do |format|
      if @pediatric.save
        format.html { redirect_to @pediatric, notice: 'Pediatric was successfully created.' }
        format.json { render :show, status: :created, location: @pediatric }
      else
        format.html { render :new }
        format.json { render json: @pediatric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pediatrics/1
  # PATCH/PUT /pediatrics/1.json
  def update
    respond_to do |format|
      if @pediatric.update(pediatric_params)
        format.html { redirect_to @pediatric, notice: 'Pediatric was successfully updated.' }
        format.json { render :show, status: :ok, location: @pediatric }
      else
        format.html { render :edit }
        format.json { render json: @pediatric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pediatrics/1
  # DELETE /pediatrics/1.json
  def destroy
    @pediatric.destroy
    respond_to do |format|
      format.html { redirect_to pediatrics_url, notice: 'Pediatric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pediatric
      @pediatric = Pediatric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pediatric_params
      params.require(:pediatric).permit(:uid, :content)
    end
end

app/helpers/pediatrics_helper.rb
module PediatricsHelper
end

app/views/pediatrics/_form.html.erb
<%= form_for(pediatric) do |f| %>
  <% if pediatric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pediatric.errors.count, "error") %> prohibited this pediatric from being saved:</h2>

      <ul>
      <% pediatric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %>
    <%= f.number_field :uid %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pediatrics/edit.html.erb
<h1>Editing Pediatric</h1>

<%= render 'form', pediatric: @pediatric %>

<%= link_to 'Show', @pediatric %> |
<%= link_to 'Back', pediatrics_path %>

app/views/pediatrics/index.html.erb
<div class="container ewing">
  <div class="header">
    <h3>CAP Cancer Protocol for Pediatric Ewing Sarcoma (v 3.2.0.0)</h3>
    <p>Based on AJCC/UICC TNM, 7th edition</p>
  </div>
  <div class="boddy">
    <form class="form-horizontal myform">
      <div class="caseno">
        <label>Case No:</label>
        <input type="text" value="" size="5" \>
      </div>
      <textarea>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</textarea>
    </form>
  </div>
  <div class="footer">
    <button type="button" class="btn btn-info">Preview</button>
    <button type="button" class="btn btn-info">PDF</button>
    <button type="button" class="btn btn-info">CAP</button>
  </div>
</div>

app/views/pediatrics/new.html.erb
<h1>New Pediatric</h1>

<%= render 'form', pediatric: @pediatric %>

<%= link_to 'Back', pediatrics_path %>

app/views/pediatrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @pediatric.uid %>
</p>

<p>
  <strong>Content:</strong>
  <%= @pediatric.content %>
</p>

<%= link_to 'Edit', edit_pediatric_path(@pediatric) %> |
<%= link_to 'Back', pediatrics_path %>