config/routes.rb
Rails.application.routes.draw do
  resources :pediatrics
  resources :caps
  get 'index/home'
  get 'index/search'
  get 'index/about'
  get 'index/contact'
  root 'index#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users
  resources :microposts
  resource :replies
  resources :identities

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :identities, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  mount_uploader :avatar, AvatarUploader
  # attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  # after_update :crop_avatar

  # def crop_avatar
  #   avatar.recreate_versions! if crop_x.present?
  # end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end


  # Include default devise modules. Others available are: :confirmable,
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,  :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  devise :database_authenticatable, :validatable, password_length: 8..128

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email


      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.info.name,
          # username: auth.info.nickname || auth.uid,
          # avatar: auth.info.image,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        #user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

    # GET /users/:id.:format
  def show
    #authorize! :read, @user
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 5 )
    @micropost = current_user.microposts.build if user_signed_in?
    @reply = current_user.replies.build if user_signed_in?
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 5 )
    @micropost = current_user.microposts.build if user_signed_in?
    @reply = current_user.replies.build if user_signed_in?
    @identity = current_user.identities.build if user_signed_in?
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        #@user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    redirect_to root_url
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email, :address, :tel, :website, :about, :mission, :avatar, :category ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/views/users/_modal.html.erb
<div class="modal fade" id="Modal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Social Link</h4>
      </div>
      <div class="modal-body form-inline">
        <%= form_for(@identity) do |f| %>
            <%=f.select :provider, options_for_select([ "facebook", "linkedin", "twitter", "google" ], "facebook"), {}, class:"form-control" %>
            <%=f.url_field :url, placeholder: "Type url...", class:"form-control" %>
            <%=f.submit 'Add', class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">

      </div>
    </div>

  </div>
</div>

app/views/users/_modal1.html.erb
<div class="modal fade" id="Modal1" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Social Link</h4>
      </div>
      <div class="modal-body form-inline">
        <%= form_for :identity, :method => 'put', html: { id: 'edit_social_form'} do |f| %>
            <!--<%=f.select :provider, options_for_select([ "facebook", "linkedin", "twitter", "google" ], "facebook"), {}, class:"form-control" %> -->
            <%=f.url_field :url, placeholder: "Type url...", class:"form-control", id: '_url' %>
            <%=f.submit 'Save', class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">

      </div>
    </div>

  </div>
</div>

app/views/users/_org.html.erb
  <div class="row usrs">
    <div class="col-md-9">
      <h2> <%= @user.name %></h2>
    </div>
    <div class="col-md-3">
      <% if @user == current_user %>
      <div class="col-md-9">
        <a class="trigger" href="#popover1">
          <h5><%= image_tag "social icons/share.png", class:"share-img"%> Share Profile</h5>
        </a>
        <div id="popover1">
          <div class="input-group">
            <input type="text" class="form-control" value="<%= user_url(current_user) %>" id="bar">
            <span class="input-group-btn">
               <button class="btn btn-primary" type="button" data-clipboard-action="copy" data-clipboard-target="#bar" id="copy">Copy</button>
            </span>
          </div><!-- /input-group -->
          To share your profile, please update your settings to allow anyone to see your profile.
        </div>
        <script>
            $('.trigger').popover({
                my: 'left bottom',
                at: 'left top',
                collision: 'flip flip'
            });

            var clip = new Clipboard('.btn');
            console.log(clip);

            $('#copy').click(function(){
                $(this).html('Copied');
            });
        </script>
      </div>
      <div class="col-md-3">
        <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>

  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="col-md-5">
        <div class="user-image" style="background: url('<%= @user.avatar_url(:large) %>')">
        </div><br>
        <h4><%= @user.following.count %> following |
        <%= @user.followers.count %> followers</h4>
        <% if user_signed_in? %>
            <% if @user != current_user %>
                <% if current_user.following?(@user) %>
                    <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                                 html: { method: :delete }) do |f| %>
                        <%= f.submit "Unfollow", class: "btn btn-primary" %>
                    <% end %>
                <% else %>
                    <%= form_for(current_user.active_relationships.build) do |f| %>
                        <div><%= hidden_field_tag :followed_id, @user.id %></div>
                        <%= f.submit "Follow", class: "btn btn-primary" %>
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
      </div>
      <div class="col-md-7 detail">
        <table class="table table-striped">
          <tr>
            <td><span class="glyphicon glyphicon-list"></span></td>
            <td>
              <%= @user.category unless @user.category == '1' %>
              <%= @user.name if @user.category == '1' %>
            </td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-globe"></span></td>
            <td><%=link_to @user.website, "http://#{@user.website}" %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-envelope"></span></td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-earphone"></span></td>
            <td><%= @user.tel %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-map-marker"></span></td>
            <td><%= @user.address %></td>
          </tr>
          <tr><td></td><td></td></tr>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <h3>Social Media</h3>
      <div class="social">
        <% @user.identities.each do|provider| %>
            <%= link_to image_tag( "social icons/#{provider.provider}.png" ), provider.url %><br>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h3>About Us</h3>
      <p class="personal-detail">
         <%= @user.about %>
      </p>
    </div>
    <div class="col-md-6">
      <h3>Mission</h3>
      <p class="personal-detail">
        <%= @user.mission %>
      </p>
    </div>
  </div>
  <div class="post">
    <h3>Posts(<%= @user.microposts.count %>)</h3>
    <% if @user.microposts.any? %>
        <table class="table table-striped">
          <thead>
          <tr>
            <th>User</th>
            <th>Post Content</th>
            <th>Time</th>
          </tr>
          </thead>
          <tbody>
          <%= render @microposts %>
          </tbody>
        </table>
        <%= will_paginate @microposts, :previous_label => '<<', :next_label => '>>' %>
    <% end %>
    <%= render 'microposts/micropost_form' if user_signed_in? %>
  </div>

app/views/users/_org_edit.html.erb
  <%= form_for @user do |f| %>
  <div class="row">
    <div class="col-md-3">
      <h2> <%= f.text_field :name, class:'form-control', value: @user.name %></h2>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
      <div class="col-md-9">

      </div>
      <div class="col-md-3">
        <%= f.submit 'Update Profile', class:'btn btn-primary' %>
      </div>

    </div>

  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="col-md-5">
        <div class="user-image" style="background: url('<%= @user.avatar %>'); background-size: 100%;">
          <%= f.file_field :avatar, id:'avatar-file', onchange: 'setimage()' %>
          <%= image_tag src="cam.png", class: "cam" %>
        </div><br><br>
        <script>
            $('.cam').bind("click" , function () {
                $('#avatar-file').click();
            });

            function setimage(){
                $('form').eq(0).submit();
            }
        </script>

        <div>
          <%= @user.following.count %> following |
          <%= @user.followers.count %> followers
        </div>
      </div>
      <div class="col-md-7 detail">
        <table class="table table-striped">
          <tr>
            <td><span class="glyphicon glyphicon-list"></span></td>
            <% category = @user.category unless @user.category == '1' %>
            <% category = @user.name if @user.category == '1'  %>
            <td><%= f.text_field :category, class:'form-control',value: category %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-globe"></span></td>
            <td><%= f.text_field :website, class:'form-control',value: @user.website %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-envelope"></span></td>
            <td><%= f.email_field :email, class:'form-control',value: @user.email %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-earphone"></span></td>
            <td><%= f.text_field :tel, class:'form-control',value: @user.tel %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-map-marker"></span></td>
            <td><%= f.text_field :address, class:'form-control',value: @user.address %></td>
          </tr>
          <tr><td></td><td></td></tr>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <h3>Social Media  <a href="#" id="add_social" data-toggle="modal" data-target="#Modal">&plus; add link</a></h3>
      <div class="social">
        <% @user.identities.each do|provider| %>
            <%= link_to image_tag( "social icons/#{provider.provider}.png" ), provider.url %>&nbsp; &nbsp;
            <%= link_to 'Delete', identity_path(provider.id), :method => :delete, 'data-confirm':'Are you sure?' %>
            <input type="hidden" value="<%= provider.id %>" class="identity_id"> &nbsp;|&nbsp;
            <input type="hidden" value="<%= provider.url %>" class="identity_url">
            <a href="#" data-toggle="modal" data-target="#Modal1" class="edit_social">Edit</a>
            <br>
        <% end %>
        <script>
          $('.edit_social').bind("click" , function (){
              index = $('.edit_socia').index($(this));
              id = $('.identity_id').eq(index).val();
              url = $('.identity_url').eq(index).val();
              $('#edit_social_form').attr('action', '/identities/' + id );
              $('#_url').val(url);
          });
        </script>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h3>About Us</h3>
        <%= f.text_area :about, value: "#{@user.about}" %>

    </div>
    <div class="col-md-6">
      <h3>Mission</h3>
      <%= f.text_area :mission, value: "#{@user.mission}" %>
    </div>
  </div>
  <% end %>
  <div class="post">
    <h3>Posts(<%= @user.microposts.count %>)</h3>
    <% if @user.microposts.any? %>
        <table class="table table-striped">
          <thead>
          <tr>
            <th>User</th>
            <th>Post Content</th>
            <th>Time</th>
          </tr>
          </thead>
          <tbody>
          <%= render @microposts %>
          </tbody>
        </table>
        <%= will_paginate @microposts, :previous_label => '<<', :next_label => '>>' %>
    <% end %>
  </div>
  </div>
  <%= render 'users/modal' %>
  <%= render 'users/modal1' %>

app/views/users/_person.html.erb
<div class="row usrs">
    <div class="col-md-9">
      <h2><%= @user.name %></h2>
    </div>
    <div class="col-md-3">
      <% if @user == current_user %>
      <div class="col-md-9">
        <a class="trigger" href="#popover1">
          <h5><%= image_tag "social icons/share.png", class:"share-img"%> Share Profile</h5>
        </a>
        <div id="popover1">
          <div class="input-group">
            <input type="text" class="form-control" value="<%= user_url(current_user) %>" id="bar">
            <span class="input-group-btn">
               <button class="btn btn-primary" type="button" data-clipboard-action="copy" data-clipboard-target="#bar" id="copy">Copy</button>
            </span>
          </div><!-- /input-group -->
          To share your profile, please update your settings to allow anyone to see your profile.
        </div>
        <script>
            $('.trigger').popover({
                my: 'left bottom',
                at: 'left top',
                collision: 'flip flip'
            });

            var clip = new Clipboard('.btn');
            console.log(clip);

            $('#copy').click(function(){
                $(this).html('Copied');
            });
        </script>
      </div>
      <div class="col-md-3">
        <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3" >
      <div class="user-image" style="background: url('<%= @user.avatar_url(:large) %>')">
      </div><br>
      <h4><%= @user.following.count %> following |
      <%= @user.followers.count %> followers</h4>
      <% if user_signed_in? %>
          <% if @user != current_user %>
              <% if current_user.following?(@user) %>
                  <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                               html: { method: :delete }) do |f| %>
                      <%= f.submit "Unfollow", class: "btn btn-primary" %>
                  <% end %>
              <% else %>
                  <%= form_for(current_user.active_relationships.build) do |f| %>
                      <div><%= hidden_field_tag :followed_id, @user.id %></div>
                      <%= f.submit "Follow", class: "btn btn-primary" %>
                  <% end %>
              <% end %>
          <% end %>
      <% end %>

      <div class="detail" >
        <table class="table table-striped">
          <tr>
            <td><span class="glyphicon glyphicon-map-marker"></span></td>
            <td><%= @user.address %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-earphone"></span></td>
            <td><%= @user.tel %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-envelope"></span></td>
            <td><%= @user.email %></td>
          </tr>
          <tr><td></td><td></td></tr>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <h3> <%= @user.name %>'s Story</h3>
      <p class="personal-detail">
        <%= @user.about %>
      </p>
    </div>
    <div class="col-md-3">
      <h3>Website</h3>
      <%= link_to @user.website, "http://#{@user.website}" %> <br>
      <h3>Social Media</h3>
      <div class="social">
        <% @user.identities.each do|provider| %>
            <%= link_to image_tag( "social icons/#{provider.provider}.png" ), provider.url %><br>
        <% end %>
      </div>
    </div>
  </div>
  <div class="post">
    <h3>Posts(<%= @user.microposts.count %>)</h3>
    <% if @user.microposts.any? %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>User</th>
        <th>Post Content</th>
        <th>Time</th>
      </tr>
      </thead>
      <tbody>
            <%= render @microposts %>
      </tbody>
    </table>
        <%= will_paginate @microposts, :previous_label => '<<', :next_label => '>>' %>
    <% end %>
    <%= render 'microposts/micropost_form' if user_signed_in? %>
  </div>

app/views/users/_person_edit.html.erb
  <%= form_for @user do |f| %>
  <div class="row usrs">
    <div class="col-md-3">
      <h2><%= f.text_field :name, class:'form-control', value: @user.name %></h2>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3">
      <div class="col-md-9">

      </div>
      <div class="col-md-3">
        <%= f.submit 'Update Profile', class:'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3" >
      <div class="user-image" style="background: url('<%= @user.avatar %>'); background-size: 100%;">
        <%= f.file_field :avatar, id:'avatar-file', onchange: 'setimage()' %>
        <%= image_tag src="cam.png", class: "cam" %>
      </div>
<script>
    $('.cam').bind("click" , function () {
        $('#avatar-file').click();
    });

    function setimage(){
        $('form').eq(0).submit();
    }
</script>
      <br><br>
      <%= @user.following.count %> following |
      <%= @user.followers.count %> followers

      <div class="detail">
        <table class="table table-striped">
          <tr>
            <td><span class="glyphicon glyphicon-map-marker"></span></td>
            <td><%= f.text_field :address, class:'form-control',value: @user.address %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-earphone"></span></td>
            <td><%= f.text_field :tel, class:'form-control',value: @user.tel %></td>
          </tr>
          <tr>
            <td><span class="glyphicon glyphicon-envelope"></span></td>
            <td><%= f.email_field :email, class:'form-control',value: @user.email %></td>
          </tr>
          <tr><td></td><td></td></tr>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <h3>My Story</h3>
      <%= f.text_area :about, value: "#{@user.about}" %>
    </div>
    <div class="col-md-3">
      <h3>Website</h3>
      <%= f.text_field :website, class:'form-control',value: @user.website %>
  <% end %>
      <h3>Social Media <a href="#" id="add_social" data-toggle="modal" data-target="#Modal">&plus; add link</a></h3>
      <div class="social">
        <% @user.identities.each do|provider| %>
            <%= link_to image_tag( "social icons/#{provider.provider}.png" ), provider.url %>
            <%= link_to 'Delete', identity_path(provider.id), :method => :delete, 'data-confirm':'Are you sure?' %>
            <input type="hidden" value="<%= provider.id %>" class="identity_id"> &nbsp;|&nbsp;
            <input type="hidden" value="<%= provider.url %>" class="identity_url">
            <a href="#" data-toggle="modal" data-target="#Modal1" class="edit_social">Edit</a>
            <br>
        <% end %>
      </div>
  <script>
      $('.edit_social').bind("click" , function (){
          index = $('.edit_socia').index($(this));
          id = $('.identity_id').eq(index).val();
          url = $('.identity_url').eq(index).val();
          $('#edit_social_form').attr('action', '/identities/' + id );
          $('#_url').val(url);
      });
  </script>
    </div>
  </div>

  <div class="post">
    <h3>Posts(<%= @user.microposts.count %>)</h3>
    <% if @user.microposts.any? %>
        <table class="table table-striped">
          <thead>
          <tr>
            <th>User</th>
            <th>Post Content</th>
            <th>Time</th>
          </tr>
          </thead>
          <tbody>
          <%= render @microposts %>
          </tbody>
        </table>
        <%= will_paginate @microposts, :previous_label => '<<', :next_label => '>>' %>
    <% end %>
  </div>

<%= render 'users/modal' %>
<%= render 'users/modal1' %>

app/views/users/_user.html.erb
<tr>
  <td>  <%= link_to image_tag( user.avatar_url(:thumb), class: 'img-circle'), user_path(user.id) if user.avatar? %></td>
  <td><%= link_to user.name, user_path(user.id) %></td>
  <td><%= user.address %></td>
  <td><%= user.website %></td>
  <td><h5>Posted <%= time_ago_in_words user.created_at %> ago</h5></td>
</tr>

app/views/users/edit.html.erb
<%= render 'users/person_edit' if @user.category == '0' %>
<%= render 'users/org_edit' if @user.category != '0' %>

app/views/users/finish_signup.html.erb
<div id="add-email">
  <div class="col-md-12">
    <div class="modal-header">
      <h1>Add Email</h1>
      </div>
        <div class="modal-body">
          <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
              <% if @show_errors && current_user.errors.any? %>
                  <div id="error_explanation">
                    <% current_user.errors.full_messages.each do |msg| %>
                        <%= msg %><br>
                    <% end %>
                  </div>
              <% end %>
              <div class="form-group">
                <label class="control-label col-md-2">Email</label>
                <div class="controls col-md-10">
                  <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
                  <p class="help-block">Please confirm your email address. No spam.</p>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                  <div class="checkbox">
                    <%= f.check_box :category %>
                    <%= f.label :Organization %>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                  <div class="checkbox">
                    <input type="checkbox">
                    <%= f.label :Individual %>
                  </div>
                </div>
              </div>
              <div class="actions">
                <%= f.submit 'Continue', :class => 'btn btn-primary' %>
              </div>
          <% end %>
          </div>
    </div>

</div>

<script>
    $('form.new_user').addClass('form-horizontal');
</script>

app/views/users/show.html.erb
<%= render 'users/person' if @user.category == '0' %>
<%= render 'users/org' if @user.category != '0' %>