config/routes.rb
Rails.application.routes.draw do
  resources :pediatrics
  resources :caps
  get 'index/home'
  get 'index/search'
  get 'index/about'
  get 'index/contact'
  root 'index#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users
  resources :microposts
  resource :replies
  resources :identities

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]
end

app/models/cap.rb
class Cap < ApplicationRecord
end

app/controllers/caps_controller.rb
class CapsController < ApplicationController
  before_action :set_cap, only: [:show, :edit, :update, :destroy]

  # GET /caps
  # GET /caps.json
  def index
    @caps = Cap.all
  end

  # GET /caps/1
  # GET /caps/1.json
  def show
  end

  # GET /caps/new
  def new
    @cap = Cap.new
  end

  # GET /caps/1/edit
  def edit
  end

  # POST /caps
  # POST /caps.json
  def create
    @cap = Cap.new(cap_params)

    respond_to do |format|
      if @cap.save
        format.html { redirect_to @cap, notice: 'Cap was successfully created.' }
        format.json { render :show, status: :created, location: @cap }
      else
        format.html { render :new }
        format.json { render json: @cap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caps/1
  # PATCH/PUT /caps/1.json
  def update
    respond_to do |format|
      if @cap.update(cap_params)
        format.html { redirect_to @cap, notice: 'Cap was successfully updated.' }
        format.json { render :show, status: :ok, location: @cap }
      else
        format.html { render :edit }
        format.json { render json: @cap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caps/1
  # DELETE /caps/1.json
  def destroy
    @cap.destroy
    respond_to do |format|
      format.html { redirect_to caps_url, notice: 'Cap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cap
      @cap = Cap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cap_params
      params.require(:cap).permit(:name)
    end
end

app/helpers/caps_helper.rb
module CapsHelper
end

app/views/caps/_form.html.erb
<%= form_for(cap) do |f| %>
  <% if cap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cap.errors.count, "error") %> prohibited this cap from being saved:</h2>

      <ul>
      <% cap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caps/edit.html.erb
<h1>Editing Cap</h1>

<%= render 'form', cap: @cap %>

<%= link_to 'Show', @cap %> |
<%= link_to 'Back', caps_path %>

app/views/caps/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container caps">
  <div class="panel-group">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>CANCER PROTOCOLS</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <table class="table table-bordered w3-table">
            <tbody>
            <tr>
              <td><a href="#">Bone and soft tissue</a></td>
              <td><a href="#">Breast</a></td>
              <td><a href="#">Central nervous system</a></td>
              <td><a href="#">Endocrine</a></td>
            </tr>
            <tr>
              <td><a href="#">Gastrointestinal</a></td>
              <td><a href="#">Genitourinary</a></td>
              <td><a href="#">Gynecologic</a></td>
              <td><a href="#">Head and neck</a></td>
            </tr>
            <tr>
              <td><a href="#">Hematologic</a></td>
              <td><a href="#">Ophthalmic</a></td>
              <td class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Pediatric</a>
                <ul class="dropdown-content">
                  <li><%= link_to 'Ewing sarcoma biopsy', pediatrics_url %></li>
                  <li><%= link_to 'Ewing sarcoma resection', pediatrics_url %></li>
                  <li><%= link_to 'Extragonadal germ cell tumor biopsy/resection', pediatrics_url %></li>
                  <li><%= link_to 'Hepatoblastoma biopsy/resection', pediatrics_url %></li>
                  <li><%= link_to 'Neuroblastoma biopsy/resection', pediatrics_url %></li>
                  <li><%= link_to 'Rhabdomyosarcoma biopsy/resection', pediatrics_url %></li>
                  <li><%= link_to 'Kidney tumors biopsy/resection', pediatrics_url %></li>
                </ul>
              </td>
              <td><a href="#">Skin</a></td>
            </tr>
            <tr>
              <td><a href="#">Torax</a></td>
              <td><a href="#">Other</a></td>
              <td><a href="#"></a></td>
              <td><a href="#"></a></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>BIOMARKER TEMPLATES</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <table class="table table-bordered w3-table">
            <tbody>
            <tr>
              <td><a href="#">Breast</a></td>
              <td><a href="#">Central nervous system</a></td>
              <td><a href="#">Endocrine</a></td>
              <td><a href="#">Gastrointestinal</a></td>
            </tr>
            <tr>
              <td><a href="#">Gynecologic</a></td>
              <td><a href="#">Head and neck</a></td>
              <td><a href="#">Hematologic</a></td>
              <td><a href="#">Skin</a></td>
            </tr>
            <tr>
              <td><a href="#">Torax</a></td>
              <td><a href="#"></a></td>
              <td><a href="#"></a></td>
              <td><a href="#"></a></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/caps/new.html.erb
<h1>New Cap</h1>

<%= render 'form', cap: @cap %>

<%= link_to 'Back', caps_path %>

app/views/caps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cap.name %>
</p>

<%= link_to 'Edit', edit_cap_path(@cap) %> |
<%= link_to 'Back', caps_path %>